name: CI

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run pytest
        run: uv run pytest
